# default_scheduler:
#   type: airflow
#   airflow_url: http://localhost:8080
#   username: admin
#   password: admin

model_naming:
  infer_names: true
  
model_defaults:
  dialect: bigquery
  start: 2020-01-01

environment_catalog_mapping:
  '^prod$': appex-data
  '^dev.*': appex-data-imports

physical_schema_mapping:
  '^base$': zz_base
  '^base_revenue$': zz_base_revenue
  '^base_product$': zz_base_product
  '^core$': zz_core
  
