gateways:
  bigquery_prod:
    connection:
      type: bigquery
      method: service-account-json
      project: appex-data
      execution_project: appex-data 
      keyfile_json: {
          "type": "service_account",
          "project_id": "appex-data",
          "private_key_id": "6e399421eabb4af0cb864224bbcdf3806ea3c364",
          "private_key": "{{ env_var('SQLMESH_BIGQUERY_PRIVATE_KEY') }}",
          # "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC51EkJUPicMZ9n\n1Icf339L5d+hTRufgtyryiTlN/OuTTj1yOwOUEsOfoDGi6hFvGiFp2C2NavzZLOo\nVIWGvthDpEcPO5a4rfiQ/DVGOlBeIvLpxLwX1WG+/Pz1trQ+lzAgmj4LYYHn72rc\nDbEwb3Qvvv9HXLhMaUfvE5XYn5crlVDGE3ADbKRTgaVTvNjLzCtk1wUO5tsHUIru\nB+DDoS6VVxK+GPqeL5Yx1pq7C2MBh8R/LqdeADULoDmDQ+0FCQGgz/RWB2MIpT8O\n04ovjHQrK6y3y/qk7XlmkxhSo8k+Eawj2sCWtbEz3+IAPLPDicQpca1CmIhm8YGH\npJqzD6vNAgMBAAECggEAM3BEy1RjjPDbfCVDRhpapUq7TW4HsG7L4K2y6tRDGsN7\neeWlGg01yYxQ3yS3bp5JnH2JcsaGk3gTlwvWbkcTnB20Ic5P2U0m2hNGN+taZcRs\n0zLHEh3Z0cE70FRDrnOxOcUYWZQjHm2Sedk8a/jeA31uMnXC+jvGUrJsLyt17/UK\n0MsOkiUeqrkQgsZLeweZVQ8TuLIk2hit3JzBGVe44WjMLH7rFI5obQfxyGS+vpsi\ntplpVc3xx7AZM/kWU/MtFNtT16qsiNuHXGyUjo97bfT84D13OEIGcS0BwiOR25Yl\n+6fLQhJ1YWAC0tl8fIekV3MvgJbckFib3Fdwvkle7QKBgQDuGs5v1KldrP9GduCz\nE8QmbsWzbAzBme7frFx505Qb1fxLyqGwckP+XQOB8pRMAaospfd4XJ3Yoi+JQTpv\nvokMNlPeDppfSNDT91r2KIG7W7WbZUYZGXVUmZmYMNhfVuFoywe2R8bvcCi+goqK\nHaN9uLdwke09RgzAaF6bsg2obwKBgQDHy6+Uwv8Kplf9aOSVIEJS4GogdcuVtJh+\nUiERwhsgFMby9hNJRpzZpFwftQalYaINLT+1PyziMh/GDzsdqxERkXvPHSdw877o\ntutylLHDE9csKNiq81smAu5sfIrL3TnAkAvpXASm3rg48VY4aJxU7oaTK2+DpJE1\n1y/MF8S1gwKBgQCK3omOQbryDqboIwdUim+5dpvJ1HfwJmZif/WDfDoCriAy2CDL\ndyle3kLgdGm3lrT4y2d1BJdvNNCCvc9mQvtNaxYpCd1RO3fIWJjtvpxDeO6Hjl5+\n3xFGYTtqvvpDSLm408lQr7ZACetJiXthqH2lIqmidwml1ggz4+th5Uv/8wKBgAzP\naICXSBb8t2OOGCnfmaEKtoNCSj1dCPIAfhJPacHS0za8xFvMZT4nJaj6yGROMD+8\nCPusA0q1gAgI7fdnAn8n3tJWwjKhzjnJkKsWEZe6a+9u5wV++Pck9PiLu7J6irto\nAPuDZOD2IsWz451WR7/CU2qYPFwqbw0OsQfa9kfVAoGBAMa67UC8kmFkrZEsWpS+\ntn8lCAfaXRhXjNypMIdNNW5gvB1pJjIyx/+Y4EMG/fhVQojfb4MJvKPwyd7cR3Mi\nUtN8FGwRhbTM+lfgP1n/pKk2DT2+mTNsV9DIM5rnWipaThiApANv/pSLnBsG2ShL\nKwgAGdbrdA0iOt4YuW7a2ylg\n-----END PRIVATE KEY-----\n",
          "client_email": "dorian-banutoiu-joinappex-com@appex-data.iam.gserviceaccount.com",
          "client_id": "114137023060001263447",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dorian-banutoiu-joinappex-com%40appex-data.iam.gserviceaccount.com",
          "universe_domain": "googleapis.com"
        }
    state_connection:
      type: postgres
      host: 34.56.124.116
      user: {{ env_var('SQLMESH_BIGQUERY_USER') }}
      password: {{ env_var('SQLMESH_BIGQUERY_PASSWORD') }}
      database: postgres
      port: 5432


# default_scheduler:
#   type: airflow
#   airflow_url: http://localhost:8080
#   username: admin
#   password: admin
#   use_state_connection: true

model_naming:
  infer_names: true
  
model_defaults:
  dialect: bigquery
  start: 2020-01-01

environment_catalog_mapping:
  '^prod$': appex-data
  '^dev.*': appex-data-imports

physical_schema_mapping:
  '^base$': zz_base
  '^base_revenue$': zz_base_revenue
  '^base_product$': zz_base_product
  '^core$': zz_core
