gateways:
  bigquery_prod:
    connection:
      type: bigquery
      method: service-account
      project: appex-data
      execution_project: appex-data
      keyfile_json: "{{ env_var('sqlmesh_bigquery_service_account_keyfile') }}"
    state_connection:
      type: postgres
      host: 34.56.124.116
      user: "{{ env_var('sqlmesh_bigquery_user') }}"
      password: "{{ env_var('sqlmesh_bigquery_password') }}"
      database: postgres
      port: 5432


# default_scheduler:
#   type: airflow
#   airflow_url: http://localhost:8080
#   username: admin
#   password: admin

model_naming:
  infer_names: true
  
model_defaults:
  dialect: bigquery
  start: 2020-01-01

environment_catalog_mapping:
  '^prod$': appex-data
  '^dev.*': appex-data-imports

physical_schema_mapping:
  '^base$': zz_base
  '^base_revenue$': zz_base_revenue
  '^base_product$': zz_base_product
  '^core$': zz_core
  
